micronaut:
  application:
    name: keyManager
  server:
    port: ${SERVER_PORT:8081}

grpc:
  server:
    port: ${SERVER_PORT:50052}
    keep_alive_time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: ${DB_URI:`jdbc:postgresql://localhost:5432/keymanagergrpc`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123}
    dialect: ${DB_DIALECT:POSTGRES}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

endpoints:
  all:
    port: ${HEALTH_PORT:8085}
    sensitive: true
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

itau:
  contas:
    url: 'http://localhost:9091/'

bcb:
  pix:
    url: 'http://localhost:8082/'